// ======================================================================
// \title  FswManagerTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for FswManager component test harness helper functions
// ======================================================================

#include "FswManagerTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void FswManagerTester ::
    connectPorts()
  {
    // Connect special input ports

    this->connect_to_cmdIn(
      0,
      this->component.get_cmdIn_InputPort(0)
    );

    // Connect special output ports

    this->component.set_cmdRegOut_OutputPort(
      0,
      this->get_from_cmdRegOut(0)
    );

    this->component.set_cmdResponseOut_OutputPort(
      0,
      this->get_from_cmdResponseOut(0)
    );

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_prmGetOut_OutputPort(
      0,
      this->get_from_prmGetOut(0)
    );

    this->component.set_prmSetOut_OutputPort(
      0,
      this->get_from_prmSetOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    this->component.set_tlmOut_OutputPort(
      0,
      this->get_from_tlmOut(0)
    );

    // Connect typed input ports

    this->connect_to_modeRequest(
      0,
      this->component.get_modeRequest_InputPort(0)
    );

    this->connect_to_schedIn(
      0,
      this->component.get_schedIn_InputPort(0)
    );
  }

  void FswManagerTester ::
    initComponents()
  {
    this->init();
    this->component.init(FswManagerTester::TEST_INSTANCE_ID);
  }

}
